name: "Setup And Run Cypress"
description: "Configure and install Cypress correctly, then launch it."
inputs:
  url:
    description: "The URL on which the tests are performed."
    required: true
  workspace:
    description: "The location of the workspace."
    required: true
runs:
  using: "composite"
  steps:
    - name: Move to the working directory
      shell: bash
      run: |
        cd "$WORKSPACE" || { echo "Workspace not found"; exit 1; }
      env:
        WORKSPACE: ${{ inputs.workspace }}

    - name: Install all dependencies
      run: pnpm install --frozen-lockfile

    - name: Run Functional tests
      shell: bash
      env:
        CYPRESS_BASE_URL: ${{ inputs.url }}
      run: pnpm exec cypress run --browser chrome
