name: "Setup Workflow"
description: "Install Node.js and the necessary dependencies."
inputs:
  node-version:
    description: "Node.js version to use. The default version is version 22."
    required: false
    default: "22"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Performant Node Package Manager (pnpm)
      uses: pnpm/action-setup@v4
