name: "🧪 Test Plan"
description: "Create a complete and structured test plan for a feature, release, or technical change."
title: "[Test Plan] <Feature or Area Name>"
labels:
  - "test plan"
body:
  - type: markdown
    attributes:
      value: |
        ## 🧪 Test Plan Template
        Please fill out this template to document the objectives, scope, approach, and validation criteria of your testing effort.

  - type: input
    id: feature
    attributes:
      label: "🔍 Feature or Area Under Test"
      description: "Which feature, module, or functionality does this test plan cover?"
      placeholder: "e.g. Payment gateway integration"

  - type: textarea
    id: objectives
    attributes:
      label: "🎯 Test Objectives"
      description: "Define what this test plan aims to validate or ensure."
      placeholder: |
        - Validate end-to-end payment flow
        - Ensure proper error handling for declined transactions
        - Confirm currency conversion accuracy

  - type: textarea
    id: scope
    attributes:
      label: "📦 Scope and Coverage"
      description: "List the areas included and excluded from this test plan."
      placeholder: |
        **In scope:**
        - Payment API endpoints
        - Front-end checkout flow

        **Out of scope:**
        - Third-party billing integrations
        - Legacy mobile app checkout

  - type: textarea
    id: preconditions
    attributes:
      label: "⚙️ Preconditions"
      description: "Describe any setup, configurations, or dependencies required before testing begins."
      placeholder: |
        - Test environment configured with valid API keys
        - Seeded test user accounts and sample transactions
        - Mock data available for sandbox mode

  - type: dropdown
    id: test_approach
    attributes:
      label: "🧰 Test Approach"
      description: "Select the testing methodology or principle used to design test cases."
      options:
        - Black-box Testing
        - White-box Testing
        - Grey-box Testing
        - Model-based Testing
        - Risk-based Testing
        - Requirements-based Testing
        - Exploratory Testing
        - Ad hoc Testing
        - Hybrid Approach

  - type: dropdown
    id: coverage_metric
    attributes:
      label: "📊 Coverage Metric (if applicable)"
      description: "Select the type of coverage metric used in this plan."
      options:
        - Statement Coverage
        - Branch Coverage
        - Path Coverage
        - Condition Coverage
        - Decision Coverage
        - Multiple Condition Coverage
        - Hit-choice Coverage
        - Not Applicable

  - type: input
    id: coverage
    attributes:
      label: "📈 Estimated Test Coverage (%)"
      description: "Provide an estimate of the test coverage for this feature or module."
      placeholder: "e.g. 85"

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "Define clear, measurable criteria that determine when this test plan is considered successful."
      placeholder: |
        - All high-priority test cases pass
        - No blocking or critical bugs remain open
        - Regression test success rate above 95%
        - Performance within acceptable limits

  - type: markdown
    attributes:
      value: |
        ---
        ## 📋 Test Cases (Structured JSON)
        Please list your test cases below using **valid JSON** format.
        This format is safer and easier to parse automatically for automation or branch creation.
        Each test case should include at least an **id**, **scenario**, and **expected_result**.

        Example:
        ```json
        [
          {
            "id": "TC-001",
            "scenario": "Successful login",
            "steps": "Enter valid credentials and submit",
            "expected_result": "User is redirected to dashboard",
            "priority": "High"
          },
          {
            "id": "TC-002",
            "scenario": "Invalid password",
            "steps": "Enter invalid password",
            "expected_result": "Error message is displayed",
            "priority": "Medium"
          }
        ]
        ```

  - type: textarea
    id: test_cases
    attributes:
      label: "🧾 Test Cases (JSON Format)"
      description: "Paste your list of test cases as a valid JSON array. Each test case must have a unique 'id'."
      placeholder: |
        [
          {
            "id": "TC-001",
            "scenario": "Successful login",
            "steps": "Enter valid credentials and submit",
            "expected_result": "User is redirected to dashboard",
            "priority": "High"
          }
        ]

  - type: dropdown
    id: priority
    attributes:
      label: "🚦 Overall Test Plan Priority"
      description: "Define the importance or urgency of executing this test plan."
      options:
        - High
        - Medium
        - Low

  - type: textarea
    id: remarks
    attributes:
      label: "💬 Additional Remarks"
      description: "Any comments, limitations, risks, or special notes about this test plan."
      placeholder: |
        - Load testing postponed until next sprint
        - Limited coverage for mobile browsers
        - Requires coordination with backend team
