name: "Publish Codecov Report"
description: "Uploads coverage reports to Codecov"
inputs:
  workspace:
    description: "The location of the workspace."
    required: true
  files:
    description: "Comma-separated explicit list of files to upload."
    required: true
  token:
    description: "Repository Codecov token."
    required: true
runs:
  using: "composite"
  steps:

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.workspace }}
      run: pnpm install --frozen-lockfile
        
    - name: Output a Coverage report
      shell: bash
      working-directory: ${{ inputs.workspace }}
      run: pnpm test:coverage --runInBand

    - name: Upload results to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: ${{ inputs.token }}
        files: ${{ format('{0}/coverage/{1}', inputs.workspace, inputs.files) }}
        disable_search: true
        fail_ci_if_error: true
