name: "Publish Codecov Report"
description: ""
inputs:
  workspace:
    description: "The location of the workspace."
    required: true
  files:
    description: "Comma-separated explicit list of files to upload."
    required: true
  token:
    description: "Repository Codecov token."
    required: true
runs:
  using: "composite"
  steps:
    - name: Move to the working directory
      shell: bash
      run: cd "${{ inputs.workspace }}"
    - name: Output a Coverage report
      shell: bash
      run: pnpm test:coverage --runInBand
    - name: Upload results to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: "${{ inputs.token }}"
        files: "coverage/${{ inputs.files }}"
        disable_search: true
        fail_ci_if_error: true
