name: Build Web Application

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: webapp

      - name: Build WebApp
        run: pnpm build
        working-directory: webapp

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-dist
          path: webapp/dist

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.web.application.to.github.pages.yml
    with:
      artifact_name: webapp-dist
