name: System Testing
on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - "webapp/**"
      - "test/system/functional/webapp/**"
      - "libs/react-material/**"
  pull_request:
    paths:
      - "webapp/**"
      - "test/system/functional/webapp/**"
      - "libs/react-material/**"
env:
  PORT: 5080
  URL: "http://localhost:5080"
permissions:
  contents: read
jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: './.github/actions/setup-workflow'
      - uses: './.github/actions/setup-workspace'
        with:
          workspace: webapp
      - name: Start Local Preview Server
        run: "./.github/scripts/starting.local.preview.server.sh --port=$PORT --path=${{ github.workspace }}/webapp"
      - uses: './.github/actions/setup-and-run-cypress'
        with:
          url: ${{ env.URL }}
          workspace: 'test/system/functional/webapp'
