name: "🧪 Test Plan Automation (JS)"

on:
  issues:
    types: [ opened, edited ]

jobs:
  validate_test_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Run Test Plan Automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/test-plan.js
